### PR TITLE
minor pedantic corrections :)

### PR DESCRIPTION
**Pull request by shishkin**

### CODE REVIEW

**Comment by forki** [comment]
mhm I'm not sure about the word `transitive` here.
how are other dependency managers call this?

@agross

**Comment by shishkin** [comment]
http://www.google.com/trends/explore#q=transitive%20dependency%2C%20indirect%20dependency

**Comment by agross** [comment]
NuGet uses the term transitive as well indirect. I have to admit indirect sounds more natural to me.

**Comment by forki** [comment]
@agross that might be german bias.

**Comment by forki** [comment]
applied to Paket itself: https://github.com/fsprojects/Paket/commit/4e5f1c58d441c74087f2f95c3696c535746c3c42

**Pull request merged**
